"""initial schema

Revision ID: 22a57415db27
Revises: 
Create Date: 2026-05-07 19:52:47.948617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '22a57415db27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.String(length=20), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performance_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'TRADER', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('broker_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.Enum('KIS', name='broker_type'), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('api_secret_enc', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Enum('REAL', 'PAPER', name='account_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('menu_key', sa.String(length=100), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('strategies',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hold_days', sa.Integer(), nullable=False),
    sa.Column('target_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('stop_loss_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('min_probability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.Column('run_interval_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_table('recommendation_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('user_strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('invest_amount_per_pick', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('is_auto_trade', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['broker_accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_analysis',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('current_situation', sa.Text(), nullable=True),
    sa.Column('historical_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('industry_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_beneficiary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('recommendations',
    sa.Column('rec_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('ai_probability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('historical_basis', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('rec_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLDING', 'TARGET_HIT', 'STOP_LOSS', 'EXPIRED', 'MANUAL_EXIT', name='position_status'), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['broker_accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rec_id'], ['recommendations.rec_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('verifications',
    sa.Column('verify_id', sa.UUID(), nullable=False),
    sa.Column('rec_id', sa.UUID(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_at_verify', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('max_high', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('max_low', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAIL', name='verification_result'), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['rec_id'], ['recommendations.rec_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verify_id'),
    sa.UniqueConstraint('rec_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifications')
    op.drop_table('positions')
    op.drop_table('recommendations')
    op.drop_table('macro_analysis')
    op.drop_table('user_strategies')
    op.drop_table('recommendation_runs')
    op.drop_table('strategies')
    op.drop_table('permissions')
    op.drop_table('broker_accounts')
    op.drop_table('users')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
