"""add_telegram_chat_id_to_users

Revision ID: 3663a3eb3f7d
Revises: b2907f846f64
Create Date: 2026-05-08 12:57:05.501072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3663a3eb3f7d'
down_revision: Union[str, None] = 'b2907f846f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
