"""add hts_id to broker_accounts

Revision ID: 39337d0cdbaa
Revises: 8754679fedd4
Create Date: 2026-05-12 09:36:19.474945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39337d0cdbaa'
down_revision: Union[str, None] = '8754679fedd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('hts_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_accounts', 'hts_id')
    # ### end Alembic commands ###
