"""add_trailing_stop_override_to_positions

Revision ID: 5a4eb9b3c332
Revises: 9e846332aa6f
Create Date: 2026-05-14 16:01:59.614083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5a4eb9b3c332'
down_revision: Union[str, None] = '9e846332aa6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_events')
    op.add_column('positions', sa.Column('trailing_stop_override', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'trailing_stop_override')
    op.create_table('news_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('kospi_at_detection', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('kosdaq_at_detection', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('kospi_change_1d', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('kospi_change_3d', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('kosdaq_change_1d', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('kosdaq_change_3d', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('verified_1d_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verified_3d_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name='news_events_pkey')
    )
    # ### end Alembic commands ###
