"""add peak_price to positions

Revision ID: 60fad4e2476a
Revises: 42b64b8b9499
Create Date: 2026-05-11 18:05:16.222117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60fad4e2476a'
down_revision: Union[str, None] = '42b64b8b9499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('peak_price', sa.Numeric(precision=18, scale=0), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'peak_price')
    # ### end Alembic commands ###
