"""add stage model columns to recommendation_runs

Revision ID: 6787d280782e
Revises: 22f19c20aa7b
Create Date: 2026-05-09 11:15:33.044994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6787d280782e'
down_revision: Union[str, None] = '22f19c20aa7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_runs', sa.Column('stage1_model', sa.String(length=100), nullable=True))
    op.add_column('recommendation_runs', sa.Column('stage2_model', sa.String(length=100), nullable=True))
    op.add_column('recommendation_runs', sa.Column('stage3_model', sa.String(length=100), nullable=True))
    op.add_column('recommendation_runs', sa.Column('stage4_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_runs', 'stage4_model')
    op.drop_column('recommendation_runs', 'stage3_model')
    op.drop_column('recommendation_runs', 'stage2_model')
    op.drop_column('recommendation_runs', 'stage1_model')
    # ### end Alembic commands ###
