"""add country currency to candidate_stocks

Revision ID: 85b15fe3da7b
Revises: 3663a3eb3f7d
Create Date: 2026-05-08 16:55:21.302637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85b15fe3da7b'
down_revision: Union[str, None] = '3663a3eb3f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_stocks', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('candidate_stocks', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_stocks', 'currency')
    op.drop_column('candidate_stocks', 'country')
    # ### end Alembic commands ###
