"""make position rec_id strategy_id nullable

Revision ID: 8754679fedd4
Revises: 60fad4e2476a
Create Date: 2026-05-11 18:16:27.864144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8754679fedd4'
down_revision: Union[str, None] = '60fad4e2476a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'strategy_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('positions', 'rec_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'rec_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('positions', 'strategy_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
