"""add candidate_filter_market_to_strategies

Revision ID: 9805532bafc0
Revises: 6d8a5365a0b8
Create Date: 2026-05-08 19:12:44.019462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9805532bafc0'
down_revision: Union[str, None] = '6d8a5365a0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('strategies', sa.Column(
        'candidate_filter', sa.String(length=20), nullable=False, server_default='mixed'
    ))
    op.add_column('strategies', sa.Column(
        'candidate_market', sa.String(length=20), nullable=False, server_default='ALL'
    ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'candidate_market')
    op.drop_column('strategies', 'candidate_filter')
    # ### end Alembic commands ###
