"""add news_events table

Revision ID: b0b705826d79
Revises: 39337d0cdbaa
Create Date: 2026-05-12 09:56:45.173728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0b705826d79'
down_revision: Union[str, None] = '39337d0cdbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
