"""add_candidate_stocks

Revision ID: b2907f846f64
Revises: 22a57415db27
Create Date: 2026-05-08 10:25:21.546354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2907f846f64'
down_revision: Union[str, None] = '22a57415db27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_SEED_STOCKS = [
    ("005930", "삼성전자",    "KOSPI", "반도체/전자"),
    ("000660", "SK하이닉스",  "KOSPI", "반도체"),
    ("035420", "NAVER",       "KOSPI", "인터넷/플랫폼"),
    ("035720", "카카오",      "KOSPI", "인터넷/플랫폼"),
    ("051910", "LG화학",      "KOSPI", "화학/배터리"),
    ("006400", "삼성SDI",     "KOSPI", "배터리"),
    ("068270", "셀트리온",    "KOSPI", "바이오"),
    ("207940", "삼성바이오로직스", "KOSPI", "바이오"),
    ("005380", "현대차",      "KOSPI", "자동차"),
    ("000270", "기아",        "KOSPI", "자동차"),
    ("012330", "현대모비스",  "KOSPI", "자동차부품"),
    ("028260", "삼성물산",    "KOSPI", "건설/지주"),
    ("096770", "SK이노베이션","KOSPI", "에너지/화학"),
    ("017670", "SK텔레콤",    "KOSPI", "통신"),
    ("030200", "KT",          "KOSPI", "통신"),
    ("003550", "LG",          "KOSPI", "지주"),
    ("034730", "SK",          "KOSPI", "지주"),
    ("009540", "HD한국조선해양", "KOSPI", "조선"),
    ("010950", "S-Oil",       "KOSPI", "정유"),
    ("086790", "하나금융지주","KOSPI", "금융"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tbl = op.create_table('candidate_stocks',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('stock_code')
    )
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    op.bulk_insert(tbl, [
        {
            "stock_code": code, "stock_name": name,
            "market": market, "sector": sector,
            "is_active": True, "notes": None, "added_at": now,
        }
        for code, name, market, sector in _SEED_STOCKS
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_stocks')
    # ### end Alembic commands ###
